apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 633324742710.dkr.ecr.us-east-1.amazonaws.com/flask-app-project:1.0
        ports:
        - containerPort: 5000
      imagePullSecrets:
          - name: regcred