apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- ./deployment-patch.yaml
- ./service-patch.yaml

images:
- name: 633324742710.dkr.ecr.us-east-1.amazonaws.com/flask-app-project
  newTag: 1.0.2

resources:
- ../base
